### ISSUE TITLE
More information needed

### ISSUE THREAD

**Issue by nickislander** [austinstig/html-local-storage-polygon-features#1] opened 2015-03-20 18:38 UTC
I gathered that Leaflet, jQuery, and DouglasCrockford's JSON are dependencies but I still need more information. I tried implementing in my site, as well as from scratch but keep getting an HTMLInputElement error on my drawnItems FeatureGroup. Won't setItem to localStorage, regardless of where fired, onClick or after drawing, with either Markers or lines. I've never committed complex JSON to HTML5 storage before so I could be missing something big.

This is really useful code, I hope you'll add to it!

**Comment by austinstig** [comment] 2015-03-20 22:52
Hi nickislander,
I would certainly like to help you out if I can.
Based on your comment I presume that your leaflet FeatureGroup of drawn items is assigned to the variable drawnItems. As in:

    var drawnItems = new L.FeatureGroup();

If this is the the case, then the code I wrote will need to be adapted.
Where I have:

    var storage_obj = JSON.stringify(JSON.decycle(items));
    localStorage.setItem('items', storage_obj);

Yours would be something like:

    var storage_obj = JSON.stringify(JSON.decycle(drawnItems));
    localStorage.setItem('drawnItems', storage_obj);

The extraction out of localStorage should be changed in a similar fashion.

Please let me know if this was helpful or not. If this doesn't work, I'm unfortunately at a bit of a loss in how to help you out. I am unable to replicate your errors with the limited information I have of your implementation, but I would like to help you.

**Comment by nickislander** [comment] 2015-03-20 22:59
Oh, I was aware of the variable naming. That wasnt an issue. I didnt know if there was some piece beyond your snippet. Ill post code here shortly. Thanks!

**Closed** 2015-03-23 22:31 UTC

**Comment by nickislander** [comment] 2015-03-24 17:15
Here is one simple attempt:

In addition to leaflet.draw plugin, I included jQuery and Douglas Crockford's JSON dependencies. I tried using various combinations of the alternate json scripts, various jQuery versons...

```javascript
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="../src/JSON/cycle.js"></script>
	<!--script src="../src/JSON/json.js"></script-->
	<!--script src="../src/JSON/json_parse.js"></script-->
	<!--script src="../src/JSON/json_parse_state.js"></script-->
	<script src="../src/JSON/json2.js"></script>	
```

Then I attempted to store the JSON on draw (as well as through button)
```javascript
<body>
	<div id="map" style="width: 800px; height: 600px; border: 1px solid #ccc"></div>
	<script>
		var osmUrl = 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
			osmAttrib = '&copy; <a href="http://openstreetmap.org/copyright">OpenStreetMap</a> contributors',
			osm = L.tileLayer(osmUrl, {maxZoom: 18, attribution: osmAttrib});
			map = new L.Map('map', {layers: [osm], center: new L.LatLng(51.505, -0.04), zoom: 13}),
			drawnItems = L.featureGroup().addTo(map);

		map.addControl(new L.Control.Draw({
			edit: { featureGroup: drawnItems }
		}));

		map.on('draw:created', function(event) {
			var layer = event.layer;
			
			// store polylines in localStorage
			var storage_obj = JSON.stringify(JSON.decycle(drawnItems));
				localStorage.setItem('drawnItems', storage_obj);
			drawnItems.addLayer(layer);
		});
	
		// on page load, extract features from html5 localStorage
		$(function(){
			var stored = JSON.parse(localStorage.getItem('drawnItems'));

			// ensure something exists
			if (stored != null && stored.length != 0){

				// resurrect the json back to an object
				stored = JSON.retrocycle(stored);
				for(var i in stored._layers){
					 var item = stored._layers[i];
					 var lyr = L.polyline(item._latlngs,{
										  color:'#22CCCC',
										  weight: 4});
					 drawnItems.addLayer(lyr);
				 };
			}
		});

	</script>
</body>
```
Wherever I call setItem I get an 'Uncaught RangeError: Maximum call stack size exceeded' error
Can you elaborate on your implementation?

**Comment by austinstig** [comment] 2015-03-25 13:15
So this has been an interesting bug hunt.
My working code:

	    <html>
		<head>
			<link rel="stylesheet" href="../leaflet.css" />
			<link rel="stylesheet" href="../src/leaflet.draw.css" />
			<link rel="stylesheet" href="https://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
			<script src="http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.js"></script>
			<script src="../src/leaflet.draw.js"></script>
			<script src="../src/esri-leaflet-src.js"></script>
			<script src="../src/cycle.js"></script>

		    <script src="https://code.jquery.com/jquery-1.9.1.js"></script>
		    <script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

			<script src="../src/edit/handler/Edit.Poly.js"></script>
			<script src="../src/edit/handler/Edit.SimpleShape.js"></script>
			<script src="../src/edit/handler/Edit.Circle.js"></script>
			<script src="../src/edit/handler/Edit.Rectangle.js"></script>
			<script src="../src/draw/handler/Draw.Feature.js"></script>
			<script src="../src/draw/handler/Draw.Polyline.js"></script>
			<script src="../src/draw/handler/Draw.Polygon.js"></script>
			<script src="../src/draw/handler/Draw.SimpleShape.js"></script>
			<script src="../src/draw/handler/Draw.Rectangle.js"></script>
			<script src="../src/draw/handler/Draw.Circle.js"></script>
			<script src="../src/draw/handler/Draw.Marker.js"></script>
			<script src="../src/ext/LatLngUtil.js"></script>
			<script src="../src/ext/GeometryUtil.js"></script>
			<script src="../src/ext/LineUtil.Intersect.js"></script>
			<script src="../src/ext/Polyline.Intersect.js"></script>
			<script src="../src/ext/Polygon.Intersect.js"></script>
			<script src="../src/Control.Draw.js"></script>
			<script src="../src/Tooltip.js"></script>
			<script src="../src/Toolbar.js"></script>
			<script src="../src/draw/DrawToolbar.js"></script>
			<script src="../src/edit/EditToolbar.js"></script>
			<script src="../src/edit/handler/EditToolbar.Edit.js"></script>
			<script src="../src/edit/handler/EditToolbar.Delete.js"></script>

			<style>
			  html,body{
		        padding:0;
		        margin:0;
		        height:100%;
		      }
		      #map{
		      	top:0px;
		      	position:absolute;
		        padding:0;
		        margin:0;
		        width:100%;
		        height:100%;
		        border: 1px solid #fff;
		      }
		      #passage-rate-dialog {
		      	top: 20px;
		      	color: #444;
		        height: auto;
		        font-family: arial;
		        margin-left: auto;
		        margin-right: auto;
		        padding: 10px;
		        position: relative;
		        width: 168px;
		        z-index: 40;
		        border: solid 2px #666;
		        border-radius: 4px;
		        background-color: #fff;
		      }
		      #prd-button {
		      	width: 162px;
		      }
		      #file-manager{
		      	position: absolute;
		      	top: 180px;
		      	padding: 10px;
		      	margin-left: 10px;
		        margin-right: auto;
		      	width: 164px;
		      	height: 109px;
		        font-family: arial;
		        z-index: 40;
		        border: solid 2px #666;
		        border-radius: 4px;
		        background-color: #fff;
		      }
		      #file-manager input{
		      	width: 163px;
		      	border-radius: 0px;
		      	border: solid 1px #666;
		      	background-color: #fff;
		      }

			</style>
		</head>
		<body>
		  	<div id="file-manager" style="display: visible">
		  		<input id="fm-clr" type="submit" value="Clear Restrictions"/>
		  		<button id="fm-sve">Save Restrictions</button>
		  		<input id="fm-clc" type="submit" value="Calculate Passage" />
		    </div>

		    <div id="map"> </div>
		  	<script>
			/*
			 * Once the Map Application has loaded
			 */
			$(function() {
				// setup variables
				var drawnItems = new L.FeatureGroup();
				/* setup the map
				 * first define the streams and basemap layers
				 * then add those layers to the map and set the first view position
				 * add any drawnItems loaded from storage into the map
				 */
			    var streams = new L.esri.TiledMapLayer("http://www.nationalatlas.gov/ArcGIS/rest/services/NationalAtlasHydroBaseMapForTerrain2/MapServer");
		    	var basemap = new L.TileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png',{
		    						styleId:999,
		    						maxzoom: 18
		    					  });
				map = new L.Map('map', {layers: [basemap,streams], center: new L.LatLng(32.3, -90.8), zoom: 10 });
				map.addLayer(drawnItems);

				/* Setup the draw controls and add it to the map
				 * then setup the draw event functions.
				 */
				var drawControl = new L.Control.Draw({
					position: 'topleft',
					draw: {
						polyline: {
							metric: true,
							shapeOptions:{
								color:'#22CCCC',
								weight: 4
							}
						},
						rectangle:false,
						polygon:false,
						circle:false,
						marker: true
					},
					edit: {
						featureGroup: drawnItems,
						remove: false
					}
				});
				map.addControl(drawControl);
				/* if local storage has been used
				 * add all of the stored features
				 * to drawnItems
				 */
				var stored = JSON.parse(localStorage.getItem('features'));
				if(stored != null && stored.length != 0){
					console.log('loading features...');
					stored = JSON.retrocycle(stored);
					for(var l in stored._layers){
						var item = stored._layers[l];
						var lyr = L.polyline(item._latlngs, {
							 color:'#22CCCC',
							 weight: 4});

						lyr.upstream_rate=item.upstream_rate;
						lyr.dwnstream_rate=item.dwnstream_rate;
						drawnItems.addLayer(lyr);
					}
		     		console.log('features loaded.');
				};
		        map.on('draw:created', function (e) {
				    /* Add the drawn feature to the feature group
					 * then open the passage rate dialog.
					 */
					drawnItems.addLayer(e.layer);
					$('#passage-rate-dialog').toggle();
				});
				map.on('draw:edited', function (e) {
					console.log('Layer edited' + e.layer);
				});
				/* setup the file manager controls
				 * loading happens on page load
				 */
				$('#fm-clr').button().click(function(click_event){
					/* clear the localStorage
					 * clear the drawnItems from map
					 * clear the drawnItems
					 */
					localStorage.features = JSON.stringify([]);
					for(var i=0;i<drawnItems.getLayers().length;i++){
						map.removeLayer(drawnItems.getLayers()[i]);
						drawnItems.removeLayer(drawnItems.getLayers()[i]);
					}
				});
				$('#fm-sve').button().click(function(click_event){
					var seen = [];
					var storage_obj = JSON.stringify(JSON.decycle(drawnItems));
					localStorage.setItem('features', storage_obj);
				});
				$('#fm-clc').button().click(function(click_event){
					console.log('send data to server...');
					/* Devolve drawnItems to simpler values
					 * then ship out using ajax
					 */
					var tosend = {};
					var layer_list = drawnItems.getLayers();
					for(var i=0;i<layer_list.length;i++){
						var lyr = layer_list[i];
						var lat_lngs = lyr.getLatLngs();
						tosend[i] = {'latlngs':[lat_lngs],
									 'up':lyr['upstream_rate'],
									 'down':lyr['dwnstream_rate']
									 };
					}
					$.ajax({
						type: "POST",
						url: 'http://0.0.0.0:1234',
						dataType: 'json',
						async:false,
						data:JSON.stringify(tosend),//JSON.decycle(drawnItems)),
						success: function(){
							console.log('The data sent.');
						},
					});
				});
		  	});
			</script>
		</body>
		</html>

I discovered that Chrome apparently has different implmentation of this than firefox. 
Firefox seems to work without any problems, but chrome is hanging up on the inability to decycle the items in cycle.js as well as some issue that prevents input HTML tags from supporting selection.
Most of my imports are from the leaflet.draw repo on github.
The cycle.js script is only required to cast js objects into strings for storage in localStorage and then rebuild the original objects in retrocycle on page load.
I have much older version of everyting but jquery and leaflet, and it looks like the problem is more related to browser updates than javascript. I am by no means an expert however.
I'm not sure how helpful this is to you, but perhaps it will help you work towards a solution.
